# 配置文件加密key
jasypt:
  encryptor:
    password: ieasy

server:
  port: 8083
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000
    min-spare-threads: 20
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ieat?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果)
    username: ENC(F6yFoRaZPl90/EttnO8DlA==)
    password: ENC(TTuPR36QunJZGaJXpvit3emgR/i9mx2y)
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: ENC(pmwqrv67USUhFszaWVwXgw==)
        login-password: ENC(TTuPR36QunJZGaJXpvit3emgR/i9mx2y)
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
      filters: stat, wall, slf4j
      validation-query: select 1 from dual
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: ENC(cFzRzuXyDO+PSMu+ZDt3Qg==)
    timeout: 3S
  servlet:
    multipart:
      max-file-size: 5M
      max-request-size: 5M
# Swagger界面内容配置
swagger:
  title: iEasy API接口文档
  description: iEasy Api Documentation
  version: 1.0.0
  termsOfServiceUrl: http://xxxxx
  contact:
    name: rabbit
    url: http://xxxx
    email: 524854935@qq.com
# 忽略鉴权url
ignored:
  urls:
  - /iEasy/common/**
  - /druid/**
  - /swagger-ui.html
  - /swagger-resources/**
  - /swagger/**
  - /test/**
#mybatis-plus配置
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/com/ctrl/education/dao/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ctrl.education.model
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 0
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: mp_
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
logging:
  file: ieasy-logs/ieasy.log